const COLS = 10;
const ROWS = 40;
const VISIBLE_ROWS = 20;
const CELL_SIZE = 30;

const LEFT_PANEL_WIDTH = 150;
const RIGHT_PANEL_WIDTH = 180;
const PANEL_PADDING = 20;

const BOARD_WIDTH = COLS * CELL_SIZE;
const BOARD_HEIGHT = VISIBLE_ROWS * CELL_SIZE;
const CANVAS_WIDTH = LEFT_PANEL_WIDTH + BOARD_WIDTH + RIGHT_PANEL_WIDTH;
const CANVAS_HEIGHT = BOARD_HEIGHT;

export {
    COLS, ROWS, CELL_SIZE, VISIBLE_ROWS,
    LEFT_PANEL_WIDTH, RIGHT_PANEL_WIDTH, PANEL_PADDING,
    BOARD_WIDTH, BOARD_HEIGHT, CANVAS_WIDTH, CANVAS_HEIGHT
};